---
title: "Project title"
author:
  - name: Author Name
    affiliation:
    - &aff1 Author Institution, City, Country.
    email: email@website.com
date: "2026-02-23"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
vignette: >
  %\VignetteIndexEntry{Project title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Programming environment

```{r Set random seed, include=FALSE}
seed <- 2026-02-23
```

```{r Load packages, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(ggpubr)
library(pbapply)
```

```{r Load functions, include=FALSE}
lapply(list.files("R/", full.names = TRUE), source)
```

```{r Set theme, include=FALSE}
my_theme_set()
```

```{r Session information, echo=FALSE}
sessionInfo()
```

# Data Preprocessing

## Raw data

```{r Read code book, include=FALSE}
code_book <- read_csv("inst/extdata/code_book.csv", show_col_types = FALSE)
```

```{r Show code book, echo=FALSE}
show_table(code_book, "code_book", "Code book.")
```

```{r Column-type string, include=FALSE}
coltype_str <- paste0(code_book$col_type, collapse = "")
```

```{r Raw data, include=FALSE}
raw_data <- read_csv("inst/extdata/raw_data.csv", col_types = coltype_str)
```

```{r State row and column numbers of raw data, echo=FALSE}
cat("Rows: ", nrow(raw_data), "\n")
cat("Columns: ", ncol(raw_data))
```

## Select variable of interest

```{r Variable of interest, include=FALSE}
voi <- "pe"
```

```{r Rename the variable as outcome and put after identifier, include=FALSE}
proc_data <-
  raw_data |>
  rename(outcome = voi) |>
  select(id, outcome, everything())
```











